# Generated by Django 5.0.1 on 2024-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.IntegerField()),
                ('customer_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('birthday', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservations_date', models.DateField()),
                ('room_number', models.IntegerField()),
                ('end_date', models.DateField()),
                ('squence_number', models.IntegerField()),
            ],
        ),
    ]
