# Generated by Django 5.0.1 on 2024-05-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meals_description_alter_meals_meal_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
