# Generated by Django 5.0.1 on 2024-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_code', models.CharField(max_length=55)),
                ('description', models.TextField()),
            ],
        ),
    ]
