# Generated by Django 5.0.1 on 2024-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_employess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('birthday', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
